<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageType>Template</PackageType>
    <PackageId>ppy.osu.Game.Templates</PackageId>
    <Title>Ez2Lazer templates</Title>
    <Authors>SK-la</Authors>
    <PackageLicenseUrl>https://github.com/SK-la/osu/blob/master/LICENCE</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/SK-la/osu/blob/master/Templates</PackageProjectUrl>
    <RepositoryUrl>https://github.com/SK-la/osu</RepositoryUrl>
    <PackageReleaseNotes>Automated release.</PackageReleaseNotes>
    <copyright>Copyright (c) 2025 ppy Pty Ltd. Ez2Lazer modifications by SK-la.</copyright>
    <Description>Templates to use when creating a ruleset for consumption in Ez2Lazer.</Description>
    <PackageTags>dotnet-new;templates;ez2lazer</PackageTags>
    <TargetFramework>netstandard2.1</TargetFramework>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoDefaultExcludes>true</NoDefaultExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Rulesets\**\*" Exclude="Rulesets\**\bin\**;Rulesets\**\obj\**" />
    <Compile Remove="**\*" />
  </ItemGroup>
</Project>
